name: shelf_hotreload
description: Wrapper to easily enable hot-reload for shelf applications.
version: 1.5.0
repository: https://github.com/felixblaschke/shelf_hotreload

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  hotreloader: ^4.2.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  shelf: ^1.4.1
